function EEG = en_dipfit(EEG, chans, rv)
if nargin < 2 || isempty(chans), chans = 1:size(EEG.icaact,1); end
if nargin < 3 || isempty(rv), rv = 15; end

EEG = pop_dipfit_settings(EEG, ...
    'coordformat',      'MNI', ...
    'hdmfile',          en_getpath('hdmfile'), ...
    'mrifile',          en_getpath('mrifile'), ...
    'chanfile',         en_getpath('chanfile'), ...
    'coord_transform',  [0.7743 -15.9248 2.61177 0.0845758 0.00105183 -1.57215 1.18029 1.07178 1.14575], ...
    'chansel',          chans);

% auto fit (coarse grid scan, then auto fine fit)
EEG = pop_multifit(EEG, ...
    chans, ...
    'threshold', rv, ...
    'plotopt', {'normlen' 'on'});

end
